ALTER TABLE questionnaire_result
    ADD COLUMN IF NOT EXISTS ethics_score      NUMERIC(7, 4) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS process_score     NUMERIC(7, 4) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS fairness_score    NUMERIC(7, 4) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS esg_score         NUMERIC(7, 4) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS ethics_debt_score NUMERIC(7, 4) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS tech_debt_score   NUMERIC(7, 4) DEFAULT NULL;

ALTER TABLE project_isep_result
    ADD COLUMN IF NOT EXISTS team_simple_avg    NUMERIC(7, 4) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS team_std_dev       NUMERIC(7, 4) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS ethics_score       NUMERIC(7, 4) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS process_score      NUMERIC(7, 4) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS fairness_score     NUMERIC(7, 4) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS esg_score          NUMERIC(7, 4) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS ethics_debt_score  NUMERIC(7, 4) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS tech_debt_score    NUMERIC(7, 4) DEFAULT NULL;


