package com.ethicalsoft.ethicalsoft_complience.domain.notification;

public enum NotificationType {
    QUESTIONNAIRE_REMINDER("QUESTIONNAIRE_REMINDER"),
    PASSWORD_RECOVERY("PASSWORD_RECOVERY"),
    NEW_USER_CREDENTIALS("NEW_USER_CREDENTIALS"),
    PROJECT_ASSIGNMENT("PROJECT_ASSIGNMENT"),
    QUESTIONNAIRE_SUBMITTED("QUESTIONNAIRE_SUBMITTED"),
    QUESTIONNAIRE_COMPLETED("QUESTIONNAIRE_COMPLETED"),
    DEADLINE_REMINDER("DEADLINE_REMINDER"),
    NOTIFICATION_DEFAULT("NOTIFICATION_DEFAULT"),
    QUESTIONNAIRE_OVERDUE("QUESTIONNAIRE_OVERDUE"),
    QUESTIONNAIRE_ISEP_CALCULATED("QUESTIONNAIRE_ISEP_CALCULATED"),
    PROJECT_OVERDUE("PROJECT_OVERDUE"),
    PROJECT_ISEP_CALCULATED("PROJECT_ISEP_CALCULATED"),
    PROJECT_UNASSIGNMENT("PROJECT_UNASSIGNMENT"),
    PROJECT_UPDATED("PROJECT_UPDATED"),
    QUESTIONNAIRE_UPDATED("QUESTIONNAIRE_UPDATED"),
    REPRESENTATIVE_ROLES_UPDATED("REPRESENTATIVE_ROLES_UPDATED"),
    QUESTIONNAIRE_DATES_UPDATED("QUESTIONNAIRE_DATES_UPDATED"),
    REPRESENTATIVE_EMAIL_CHANGED("REPRESENTATIVE_EMAIL_CHANGED"),
    PROJECT_DEADLINE_UPDATED("PROJECT_DEADLINE_UPDATED"),
    QUESTIONNAIRE_REMOVED("QUESTIONNAIRE_REMOVED"),
    QUESTIONNAIRE_RESCHEDULED("QUESTIONNAIRE_RESCHEDULED"),
    PROJECT_DEADLINE_EXCEEDED_WARNING("PROJECT_DEADLINE_EXCEEDED_WARNING"),
    NEXT_QUESTIONNAIRE_STARTING_SOON("NEXT_QUESTIONNAIRE_STARTING_SOON"),
    NON_COMPLIANCE_BULLETIN_EMITTED("NON_COMPLIANCE_BULLETIN_EMITTED");

    private final String templateKey;

    NotificationType(String templateKey) {
        this.templateKey = templateKey;
    }

    public String templateKey() {
        return templateKey;
    }
}
